[workspace]
members = [
    "ractor",
    "ractor-derive"
]

[patch.crates-io]
ractor = { path = "ractor" }
ractor-derive = { path = "ractor-derive" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
