cargo-features = ["edition2021"]

[package]
name = "ractor"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ractor-derive = { version = "0.1", optional = true }

tokio = { version = "1.9", features = ["full"], optional = true }
async-std = { version = "1.9.0", features = ["unstable"], optional = true }
utils-soeur = "0.1"
num_cpus = "1.13.0"
crossfire = "0.1.5"
futures = "0.3.16"
async-trait = "0.1.51"
once_cell = "1.8.0"
thiserror = "1.0"
rayon = "1.5.1"

[dev-dependencies]
tokio = { version = "1.9", features = ["full"] }
http = "0.2.4"
tokio-util = { version = "0.6.7", features = ["codec"] }
httparse = "1.4.1"
bytes = "1.0.1"
time = "0.1"
hyper = { version = "0.14.11", features = ["full"] }
mimalloc = { version = "0.1.26", default-features = false }


[features]
default = ["derive", "use_tokio"]
derive = ["ractor-derive"]
use_tokio = ["tokio"]
use_async-std = ["async-std"]

[[bench]]
name = "fib"
