[package]
name = "ractor-derive"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1"
syn = { version = "1", features = ["derive"] }
proc-macro2 = "1"

[lib]
proc-macro = true
